title: Portfólio de Carlos Willian
logo: /assets/img/perfil.jpg
description: Um portfólio profissional destacando minhas habilidades e projetos.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
