title: Portfólio de Carlos
logo: /assets/img/perfil.jpg
description: Um portfólio profissional destacando minhas habilidades e projetos.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
