title: Minimal theme
logo: /https://github.com/carloswilll/carloswilll.github.io/blob/main/_layouts/perfil.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
